triggers:
   - name: triggersp1
     type: trigger
     version:
       counter: 4
       
   - name: triggersp2
     type: trigger
     version:
       counter: 3
       
   - name: triggersp3
     type: trigger
     version:
       counter: 1
