jobs:
  - name: cli-manifest1
    type: manifest
    steps:
      - IN: cli-image1
        pull: true

  - name: cli-runshecr
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configaws
        scope: ecr
      - TASK:
        #- script: ls
        - script: echo CLICONFIGAWS_INTEGRATION_ACCESSKEY=$CLICONFIGAWS_INTEGRATION_ACCESSKEY
        - script: echo AWSCLICONFIG_INTEGRATION_SECRETKEY=${#CLICONFIGAWS_INTEGRATION_SECRETKEY}
        - script: echo AWSCLICONFIG_NAME=$CLICONFIGAWS_NAME
        - script: echo AWSCLICONFIG_ID=$CLICONFIGAWS_ID
        - script: echo AWSCLICONFIG_TYPE=$CLICONFIGAWS_TYPE
        - script: echo AWSCLICONFIG_INTEGRATION_TYPE=$CLICONFIGAWS_INTEGRATION_TYPE
        - script: echo AWSCLICONFIG_OPEARATION=$CLICONFIGAWS_OPERATION
        - script: echo AWSCLICONFIG_PATH=$CLICONFIGAWS_PATH
        - script: echo AWSCLICONFIG_POINTER_REGION=$CLICONFIGAWS_POINTER_REGION
        - script: echo AWSCLICONFIG_POINTER_CLUSTERNAME=$CLICONFIGAWS_POINTER_CLUSTERNAME
        - script: echo AWSCLICONFIG_VERSIONNUMBER=$CLICONFIGAWS_VERSIONNUMBER
        - script: echo AWSCLICONFIG_VERSIONNAME=$CLICONFIGAWS_VERSIONNAME
        - script: echo AWSCLICONFIG_VERSIONID=$CLICONFIGAWS_VERSIONID
        - script: docker pull 742038439709.dkr.ecr.us-east-1.amazonaws.com/sample_php
        
  - name: cli-runshaws
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configaws
        scope: aws
      - TASK:
        - script: eb --version
        - script: echo CLICONFIGAWS_INTEGRATION_ACCESSKEY=$CLICONFIGAWS_INTEGRATION_ACCESSKEY
        - script: echo AWSCLICONFIG_INTEGRATION_SECRETKEY=${#CLICONFIGAWS_INTEGRATION_SECRETKEY}
        - script: echo AWSCLICONFIG_NAME=$CLICONFIGAWS_NAME
        - script: echo AWSCLICONFIG_ID=$CLICONFIGAWS_ID
        - script: echo AWSCLICONFIG_TYPE=$CLICONFIGAWS_TYPE
        - script: echo AWSCLICONFIG_INTEGRATION_TYPE=$CLICONFIGAWS_INTEGRATION_TYPE
        - script: echo AWSCLICONFIG_OPEARATION=$CLICONFIGAWS_OPERATION
        - script: echo AWSCLICONFIG_PATH=$CLICONFIGAWS_PATH
        - script: echo AWSCLICONFIG_POINTER_REGION=$CLICONFIGAWS_POINTER_REGION
        - script: echo AWSCLICONFIG_POINTER_CLUSTERNAME=$CLICONFIGAWS_POINTER_CLUSTERNAME
        - script: echo AWSCLICONFIG_VERSIONNUMBER=$CLICONFIGAWS_VERSIONNUMBER
        - script: echo AWSCLICONFIG_VERSIONNAME=$CLICONFIGAWS_VERSIONNAME
        - script: echo AWSCLICONFIG_VERSIONID=$CLICONFIGAWS_VERSIONID      
        
  - name: cli-runshdocker
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configdocker
      - TASK:
        - script: echo CLICONFIGDOCKER_INTEGRATION_URL=$CLICONFIGDOCKER_INTEGRATION_URL
        - script: echo CLICONFIGDOCKER_INTEGRATION_USERNAME=$CLICONFIGDOCKER_INTEGRATION_USERNAME
        - script: echo CLICONFIGDOCKER_INTEGRATION_PASSWORD=${#CLICONFIGDOCKER_INTEGRATION_PASSWORD}
        - script: echo CLICONFIGDOCKER_INTEGRATION_EMAIL=$CLICONFIGDOCKER_INTEGRATION_EMAIL
 
  - name: cli-runshgcl
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configgcl
      - TASK:
        - script: echo CLICONFIGGCL_INTEGRATION_JSON_KEY=${#CLICONFIGDCL_INTEGRATION_JSON_KEY}
        - script: docker push gcr.io/vidya-project/node1-img:master.33
  
  - name: cli-runshjfrog
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configjfrog
      - TASK:
        - script: echo CLICONFIGJFROG_INTEGRATION_URL=$CLICONFIGJFROG_INTEGRATION_URL
        - script: echo CLICONFIGJFROG_INTEGRATION_USERNAME=$CLICONFIGJFROG_INTEGRATION_USERNAME
        - script: echo CLICONFIGJFROG_INTEGRATION_PASSWORD=${#CLICONFIGJFROG_INTEGRATION_PASSWORD}
        - script: jfrog rt dl test-jfrog-ship/testoct.sh
        
  - name: cli-runshkube
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configkube
      - TASK:
        - script: echo CLICONFIGKUBE_INTEGRATION_KUBECONFIGCONTENT=${#CLICONFIGKUBE_INTEGRATION_KUBECONFIGCONTENT}
  
  - name: cli-runshquay
    type: runSh
    steps:
      - IN: cli-repo
      - IN: cli-configquay
      - TASK:
        - script: echo CLICONFIGQUAY_INTEGRATION_ACCESSTOKEN=${#CLICONFIGQUAY_INTEGRATION_ACCESSTOKEN}
        - script: echo CLICONFIGQUAY_INTEGRATION_USERNAME=$CLICONFIGQUAY_INTEGRATION_USERNAME
        - script: echo CLICONFIGQUAY_INTEGRATION_PASSWORD=${#CLICONFIGQUAY_INTEGRATION_PASSWORD}
        - script: echo CLICONFIGQUAY_INTEGRATION_EMAIL=$CLICONFIGQUAY_INTEGRATION_EMAIL
        - script: docker pull quay.io/revathird/samplenode_test
        
