jobs:
  - name: test-man
    type: manifest
    steps:
      - IN: test-image
      - TASK: managed
  - name: test-man1
    type: manifest
    steps:
     # - IN: test-image  
      - IN: test-image-t
      - TASK: managed
  - name: test-man2
    type: manifest
    steps:
     # - IN: test-image  
      - IN: test-image-t1
      - IN: trigger-dv-man
      - TASK: managed
