triggers:
   - name: triggersp1
     type: trigger
     version:
       counter: 8
       
   - name: triggersp2
     type: trigger
     version:
       counter: 7
       
   - name: triggersp3
     type: trigger
     version:
       counter: 1
