jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params
        applyTo:
          - dv-image
      - GET: trigger-dv-man
      - GET: dv-image-testing_for_a_long_name
      - GET: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      
      
  - name: dv-man1
    type: manifest
    steps:
      - GET: dv-image
      - GET: trigger-dv-man
      - GET: dv-image1
      - GET: dv-image2
      - GET: dv-image-testing_for_a_long_name
      - GET: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - PUT: dv-opts
      - PUT: dv-params
      - PUT: image1
      - PUT: image2
     
  - name: dv-man2
    type: manifest
    steps:
      #- GET: dv-image  
      - GET: dv-man
      - GET: dv-image-testing_for_a_long_name
      - GET: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
  - name: dv-man3
    type: manifest
    steps:
      #- GET: dv-image  
      - GET: dv-man2
      - GET: dv-image-testing_for_a_long_name
      - GET: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - GET: s1
  - name: s1
    type: manifest
    steps:
      #- GET: dv-image  
      - GET: image1
      - GET: dv-opts
      - GET: dv-params
  - name: s2
    type: manifest
    steps:
      #- GET: dv-image  
      - GET: image1
      
