jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
      - IN: dv-opts
      - IN: dv-params
        applyTo:
          - dv-image
      - IN: trigger-dv-man
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - TASK: managed
      
      
  - name: dv-man1
    type: manifest
    steps:
      - IN: dv-image
      - IN: trigger-dv-man
      - IN: dv-image1
      - IN: dv-image2
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - TASK: managed
      - OUT: dv-opts
      - OUT: dv-params
      - OUT: image1
      - OUT: image2
     
  - name: dv-man2
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: dv-man
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - IN: s2
      - TASK: managed
  - name: dv-man3
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: dv-man2
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - IN: dv-image
      - IN: s2
      - IN: s1
      - TASK: managed
      - OUT: dv-image-xyz
      - OUT: dv-image-xy
      - OUT: dv-image-x
  - name: s1
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: image1
      - IN: dv-opts
      - IN: dv-params
      - TASK: managed
  - name: s2
    type: manifest
    steps:
  
      - IN: image1
      - TASK: managed
      
      
