triggers:
   - name: triggersp1
     type: trigger
     version:
       counter: 2
       
   - name: triggersp2
     type: trigger
     version:
       counter: 1
       
   - name: triggersp3
     type: trigger
     version:
       counter: 1
