jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params
        applyTo:
          - dv-image
      - GET: trigger-dv-man
      
  - name: dv-man1
    type: manifest
    steps:
      - GET: dv-image
      - GET: trigger-dv-man
      - GET: dv-image1
      - GET: dv-image2
      - PUT: dv-opts
      - PUT: dv-params
      
  - name: dv-man2
    type: manifest
    steps:
      - GET: dv-image   
 
  - name: release-one
    type: release
    options:
      action: minor
    steps:
      - GET: version-resource
      - GET: dv-man
