triggers:
   - name: triggersp1
     type: trigger
     version:
       counter: 6
       
   - name: triggersp2
     type: trigger
     version:
       counter: 5
       
   - name: triggersp3
     type: trigger
     version:
       counter: 1
