jobs:
  - name: test-man
    type: manifest
    steps:
      - IN: test-image
  - name: test-man1
    type: manifest
    steps:
     # - IN: test-image  
      - IN: test-image-t
  - name: test-man2
    type: manifest
    steps:
     # - IN: test-image  
      - IN: test-image-t
