jobs:
  - name: aws-manifest1
    type: manifest
    steps:
      - IN: aws-image1
        pull: true
      - IN: aws-ecscluster
      - IN: aws-params1
      #  applyTo:
       #   - aws-image1
      - TASK: managed
      - IN: aws-trigger1
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
     
  - name: aws-manifest2
    type: manifest
    steps:
      - IN: aws-image2
        pull: false
      - IN: aws-dopts1
      - IN: aws-trigger2
      - IN: aws-params2
        
  - name: aws-deploybluegreendownlevel
    type: deploy
    steps:
      - IN: aws-manifest1
      - IN: aws-ecscluster
      - TASK: managed
        deployMethod: blueGreen
        
  - name: aws-deployupgradedownlevel
    type: deploy
    steps:
      - IN: aws-manifest1
      - IN: aws-ecscluster
      - TASK: managed
        deployMethod: upgarde
        
  - name: aws-deployreplacedownlevel
    type: deploy
    steps:
      - IN: aws-manifest1
      - IN: aws-ecscluster
      - TASK: managed
        deployMethod: replace
  
  - name: aws-deploybluegreentoplevel
    type: deploy
    method: blueGreen
    workflow: parallel
    steps:
      - IN: aws-manifest1
      - IN: aws-manifest2
      - IN: aws-ecscluster
        
  - name: aws-deployupgradetoplevel
    type: deploy
    method: upgrade
    workflow: parallel
    steps:
      - IN: aws-manifest1
      - IN: aws-manifest2
      - IN: aws-ecscluster
        
  - name: aws-deployreplacetoplevel
    type: deploy
    method: replace
    workflow: parallel
    steps:
      - IN: aws-manifest1
      - IN: aws-manifest2
      - IN: aws-ecscluster
        
  - name: aws-runshclis
    type: runSh
    steps:
      - IN: aws-repo
      - IN: aws-cliconfig
      - TASK:
        - script: ls
        - script: echo AWSCLICONFIG_INTEGRATION_ACCESSKEY=$AWSCLICONFIG_INTEGRATION_ACCESSKEY
        - script: echo AWSCLICONFIG_INTEGRATION_SECRETKEY=${#AWSCLICONFIG_INTEGRATION_SECRETKEY}
        - script: echo AWSCLICONFIG_NAME=$AWSCLICONFIG_NAME
        - script: echo AWSCLICONFIG_ID=$AWSCLICONFIG_ID
        - script: echo AWSCLICONFIG_TYPE=$AWSCLICONFIG_TYPE
        - script: echo AWSCLICONFIG_INTEGRATION_TYPE=$AWSCLICONFIG_INTEGRATION_TYPE
        - script: echo AWSCLICONFIG_OPEARATION=$AWSCLICONFIG_OPERATION
        - script: echo AWSCLICONFIG_PATH=$AWSCLICONFIG_PATH
        - script: echo AWSCLICONFIG_POINTER_REGION=$AWSCLICONFIG_POINTER_REGION
        - script: echo AWSCLICONFIG_POINTER_CLUSTERNAME=$AWSCLICONFIG_POINTER_CLUSTERNAME
        - script: echo AWSCLICONFIG_VERSIONNUMBER=$AWSCLICONFIG_VERSIONNUMBER
        - script: echo AWSCLICONFIG_VERSIONNAME=$AWSCLICONFIG_VERSIONNAME
        - script: echo AWSCLICONFIG_VERSIONID=$AWSCLICONFIG_VERSIONID
