jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
      - IN: dv-opts
      - IN: dv-params
      - IN: s6
        applyTo:
          - dv-image
      - IN: trigger-dv-man
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - TASK: managed
  - name: dv
    type: manifest
    steps:
      - IN: dv-image
      - TASK: managed
    flags:
      - dv
  - name: dv-test
    type: manifest
    steps:
      - IN: dv-man6
      - IN: dv-man-8
      - IN: dv-man-7
      - TASK: managed
  - name: dv-inc
    type: manifest
    steps:
      - IN: dv-image
    flags:
      - dv-inc
  - name: dv-man1
    type: manifest
    steps:
      - IN: dv-image
      - IN: trigger-dv-man
      
      - TASK: managed
    
      
     
  - name: dv-man2
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: dv-man
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - IN: s2
     # - IN: s2
      - TASK: managed
  - name: dv-man3
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: dv-man2
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - IN: dv-image
     # - IN: s2
      - IN: s1-test-for-the-long-name-12346
      - IN: s2
      - TASK: managed
      - OUT: dv-image-xyz
      - OUT: dv-image-xy
      - OUT: dv-image-x
  - name: dv-man4
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: dv-man2
     
      - IN: s1-test-for-the-long-name-12346
     
      - TASK: managed
     
  - name: dv-man5
    type: manifest
    steps:
      - IN: dv-image-xyz
      - IN: dv-image-xy
      - IN: dv-image-x   
      - IN: s1-test-for-the-long-name-12346
      - TASK: managed
    flags:
      - dv-man5
  
  - name: dv-man6
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - IN: s1-test-for-the-long-name-12346
      - TASK: managed
    flags:
      - dv-man6
      
      
  - name: s1-test-for-the-long-name-12346
    type: manifest
    steps:
      #- GET: dv-image  
      - IN: image1
      - IN: dv-opts
      - IN: dv-params
      - TASK: managed
    flags:
      - s1-test-for-the-long-name-12346
  - name: s2
    type: manifest
    steps:
      - IN: image1
      - TASK: managed
    flags:
      - s2
      
  - name: s3
    type: manifest
    steps:
  
      - IN: image123
      - IN: dv-inc
      - TASK: managed
      - OUT: dv-image-xyzw
  - name: s4
    type: manifest
    steps:
      - IN: image1234
      - IN: image12345
      - TASK: managed
      - OUT: image12346
  - name: s5
    type: manifest
    steps:
      - IN: image123467324242
      - TASK: managed
       
  
     # - OUT: image123467890
  - name: s6
    type: manifest
    steps:
      - IN: xyz
      - TASK: managed
      - OUT: imagetest
      
      
  - name: dv-man-7
    type: manifest
    steps:
      - IN: s1-test-for-the-long-name-12346
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - TASK: managed
        
  - name: dv-man-8
    type: manifest
    steps:
      - IN: s1-test-for-the-long-name-12346
      - IN: dv-image-testing_for_a_long_name
      - IN: dv-image-testing_for_a_long_name_dv-image-testing_for_a_long_name_test_123
      - TASK: managed
      
  - name: invalid_input
    type: manifest
    steps:
      - IN: imagetest-invalid
      - TASK: managed    
      
